### PR TITLE
Create Settings Screen

### PR DESCRIPTION
**Pull request by BolajiOlajide**
Resolves #NUMBER

**Overall change:**
- Create the settings page according to the Figma mock

---

- [ ] I have assigned myself to this PR and the corresponding issues

**Testing:**

- [ ] Automated (jest) tests added (for new features) or updated (for existing features)
Screenshot_20200425-203005

### CODE REVIEW

**Comment by mykeels** [comment]
Could you include a screenshot?

**Comment by mykeels** [comment]
Does the label beside the textbox respond to the radio button change yet? Like, display "%" when that is selected?

**Comment by BolajiOlajide** [comment]
Yes, it does. It, however, displays `percent` and `cents` instead of `%` and `c`.
Do you think I should change it to the symbol, I think that's smoother yeah?

**Comment by mykeels** [comment]
Yeah, I think % is more recognisable. Cents can remain the same.

**Comment by BolajiOlajide** [comment]
Done.

**Pull request merged**
